language: cpp

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - doxygen docs/Doxyfile
  - mkdir build
  - cd build
  - cmake .. -DUSE_ARM_COMPILER=OFF
  - cmake --build . --target runTests
  - ctest

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master