language: cpp
compiler: gcc

os: linux
addons:
  apt:
    packages:
      - doxygen
      - g++-7
    sources:
      - ubuntu-toolchain-r-test

# Build your code e.g. by calling make
script:
  - doxygen docs/Doxyfile
  - mkdir build
  - cd build
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .. -DUSE_ARM_COMPILER=OFF -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build . --target runTests
  - ctest

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master